#!/usr/bin/env bash
# Emits the Jekyll data file behind the version marker under every document
# on the documentation site (docs/_layouts/default.html reads it as
# site.data.doc_versions).
#
# Usage: doc-versions.sh [repo-root] > docs/_data/doc_versions.yml
#
# A document's version is the first release (tag vMAJOR.MINOR.PATCH) that
# contains the last commit that changed the document or one of the local
# images it embeds. When no release contains
# that commit yet, the version is dashboard/VERSION as of that commit and the
# document is marked `unreleased`, i.e. the page already describes changes
# that no release ships yet. Needs the full history and the tags
# (actions/checkout with fetch-depth: 0).
#
# A document that describes one component (a service, the installer, a Home
# Assistant integration) names it in its front matter, `component: <id>` with
# an id from scripts/version/components.json. The marker then also carries
# that component's version, read from its version file at the release tag, or
# at the document's last commit when it is unreleased.
set -euo pipefail

root="${1:-.}"
cd "$root"

version_file=dashboard/VERSION

latest_release="$(git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"

components=scripts/version/components.json

# component_of FILE: the `component:` value from FILE's front matter, if any.
component_of() {
  awk 'NR == 1 && $0 != "---" { exit } NR > 1 && $0 == "---" { exit }
       NR > 1 && sub(/^component:[ \t]*/, "") { gsub(/["\047\r]/, ""); sub(/[ \t]+$/, ""); print; exit }' "$1"
}

# component_version ID COMMIT: "<label>\t<vX.Y.Z>" for component ID as of
# COMMIT, empty when the id is unknown or its version file did not exist yet.
component_version() {
  python3 - "$1" "$2" "$components" <<'PY'
import json, subprocess, sys

cid, commit, registry = sys.argv[1:]
entry = next((c for c in json.load(open(registry))["components"] if c["id"] == cid), None)
if entry is None:
    sys.exit(f"doc-versions: unknown component {cid!r}")
shown = subprocess.run(["git", "show", f"{commit}:{entry['version_file']}"],
                       capture_output=True, text=True)
if shown.returncode != 0:
    sys.exit(0)
if entry["version_file"].endswith(".json"):
    version = str(json.loads(shown.stdout).get("version", "")).strip()
else:
    version = shown.stdout.strip()
if not version:
    sys.exit(0)
if not version.startswith("v"):
    version = "v" + version
label = entry["label"] + (" service" if entry["kind"] == "service" else "")
print(f"{label}\t{version}")
PY
}

# page_paths FILE: FILE plus the local images it embeds (Markdown images and
# <img src>), so a page counts as changed when one of its screenshots changed.
page_paths() {
  local file="$1" ref path
  printf '%s\n' "$file"
  grep -oE '\]\([^)[:space:]]+|src="[^"]+' "$file" | sed -E 's/^\]\(//; s/^src="//' \
    | grep -E '^[^:]*\.(png|jpe?g|gif|svg|webp)$' | while IFS= read -r ref; do
      path="$(realpath -m --relative-to=. "$(dirname "$file")/$ref")"
      [ -f "$path" ] && printf '%s\n' "$path"
    done | sort -u || true
}

# first_release COMMIT: the oldest release tag that contains COMMIT, if any.
first_release() {
  git tag -l 'v*' --contains "$1" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | head -1 || true
}

echo "# Generated by scripts/docs/doc-versions.sh during the Pages build. Do not edit."
echo "latest_release: \"$latest_release\""
echo "pages:"

# _internal/ is not published and redirects/ only holds redirect stubs.
git ls-files -- 'docs/*.md' ':!docs/_internal/**' ':!docs/redirects/**' | sort | while IFS= read -r file; do
  mapfile -t paths < <(page_paths "$file")
  commit="$(git log -1 --format=%H -- "${paths[@]}")"
  release=""
  [ -z "$commit" ] || release="$(first_release "$commit")"
  if [ -n "$release" ]; then
    version="$release"
    commit="$release"
    unreleased=false
  else
    if [ -n "$commit" ]; then
      version="$(git show "$commit:$version_file" 2>/dev/null | tr -d '[:space:]' || true)"
    else
      commit=HEAD
      version="$(tr -d '[:space:]' < "$version_file")"
    fi
    unreleased=true
  fi
  [ -n "$version" ] || continue

  extra=""
  component="$(component_of "$file")"
  if [ -n "$component" ]; then
    found="$(component_version "$component" "$commit")"
    if [ -n "$found" ]; then
      extra=", component: \"${found%%$'\t'*}\", component_version: \"${found#*$'\t'}\""
    fi
  fi

  echo "  \"${file#docs/}\": { version: \"$version\", unreleased: $unreleased$extra }"
done
