#!/usr/bin/env bash
# Emits the Jekyll data file behind the version marker under every document
# on the documentation site (docs/_layouts/default.html reads it as
# site.data.doc_versions).
#
# Usage: doc-versions.sh [repo-root] > docs/_data/doc_versions.yml
#
# A document's version is dashboard/VERSION as of the last commit that changed
# the document. It is marked `unreleased` when that version is newer than the
# latest release tag (vMAJOR.MINOR.PATCH), i.e. the page already describes
# changes that no release ships yet. Needs the full history and the tags
# (actions/checkout with fetch-depth: 0).
set -euo pipefail

root="${1:-.}"
cd "$root"

version_file=dashboard/VERSION

latest_release="$(git tag -l 'v*' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -1 || true)"

# newer A B: true when version A sorts strictly after version B.
newer() {
  [ "$1" != "$2" ] && [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | tail -1)" = "$1" ]
}

echo "# Generated by scripts/docs/doc-versions.sh during the Pages build. Do not edit."
echo "latest_release: \"$latest_release\""
echo "pages:"

git ls-files -- 'docs/*.md' | sort | while IFS= read -r file; do
  commit="$(git log -1 --format=%H -- "$file")"
  if [ -n "$commit" ]; then
    version="$(git show "$commit:$version_file" 2>/dev/null | tr -d '[:space:]' || true)"
  else
    version="$(tr -d '[:space:]' < "$version_file")"
  fi
  [ -n "$version" ] || continue

  unreleased=false
  if [ -z "$latest_release" ] || newer "$version" "$latest_release"; then
    unreleased=true
  fi

  echo "  \"${file#docs/}\": { version: \"$version\", unreleased: $unreleased }"
done
