#!/usr/bin/env python3
"""Emits the Jekyll data file behind the version overview on the
documentation site (docs/developing/versions.md reads it as
site.data.release_versions).

Usage: release-versions.py [repo-root] > docs/_data/release_versions.yml

Lists every release tag (vMAJOR.MINOR.PATCH), newest first, with the version
of each component from scripts/version/components.json as of that tag. A
component whose version file did not exist yet at a tag is left out of that
release. `status` is "new" for a component the previous release did not
have, "changed" for a version that differs from it and "same" otherwise.
Needs the full history and the tags (actions/checkout with fetch-depth: 0).
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

TAG_RE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")


def git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)


def version_at(root: Path, tag: str, version_file: str) -> str | None:
    shown = git(root, "show", f"{tag}:{version_file}")
    if shown.returncode != 0:
        return None
    if version_file.endswith(".json"):
        version = str(json.loads(shown.stdout).get("version", "")).strip()
    else:
        version = shown.stdout.strip()
    if not version:
        return None
    return version if version.startswith("v") else "v" + version


def quote(value: str) -> str:
    return json.dumps(value)


def main() -> None:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    registry = json.loads((root / "scripts/version/components.json").read_text())["components"]

    tags = [t for t in git(root, "tag", "-l", "v*").stdout.split() if TAG_RE.match(t)]
    tags.sort(key=lambda t: tuple(int(n) for n in TAG_RE.match(t).groups()))

    releases = []
    previous: dict[str, str] = {}
    for tag in tags:
        date = git(root, "log", "-1", "--format=%cs", tag).stdout.strip()
        components = []
        for entry in registry:
            version = version_at(root, tag, entry["version_file"])
            if version is None:
                continue
            components.append({
                "label": entry["label"],
                "kind": entry["kind"],
                "bundle": entry["bundle"],
                "version": version,
                "status": ("new" if entry["id"] not in previous
                           else "changed" if previous[entry["id"]] != version else "same"),
            })
            previous[entry["id"]] = version
        releases.append({"tag": tag, "date": date, "components": components})

    print("# Generated by scripts/docs/release-versions.py during the Pages build. Do not edit.")
    print("releases:")
    for release in reversed(releases):
        print(f"  - tag: {quote(release['tag'])}")
        print(f"    date: {quote(release['date'])}")
        print("    components:")
        for c in release["components"]:
            print(f"      - {{ label: {quote(c['label'])}, kind: {quote(c['kind'])}, "
                  f"bundle: {str(c['bundle']).lower()}, version: {quote(c['version'])}, "
                  f"status: {c['status']} }}")


if __name__ == "__main__":
    main()
