#!/usr/bin/env python3
"""Sync the shared battery_soc_core package into the Home Assistant integration.

The Home Assistant custom component ships a *vendored* copy of
``libs/battery_soc_core/battery_soc_core``. That copy is a derived artifact: it
is regenerated by this script and never edited by hand. ``--check`` reports
drift and is wired into CI (the *Vendored artefacts in sync* job) and the HA
test suite (``integrations/homeassistant/tests/test_vendor_sync.py``).

Usage (from anywhere inside the repo)::

    .venv/bin/python scripts/vendor_core.py            # sync src -> vendored copy
    .venv/bin/python scripts/vendor_core.py --check    # drift detector (exit 1 on drift)

Stdlib only.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

VENDOR_MARKER = "_VENDORED.md"
SRC_REL = Path("libs/battery_soc_core/battery_soc_core")
DST_REL = Path(
    "integrations/homeassistant/custom_components/battery_soc/battery_soc_core"
)


def repo_root() -> Path:
    out = subprocess.check_output(["git", "rev-parse", "--show-toplevel"])
    return Path(out.decode().strip())


def _iter_py(base: Path):
    """Yield every ``*.py`` under ``base`` except those in a ``tests`` or
    ``__pycache__`` directory."""
    if not base.exists():
        return
    for path in sorted(base.rglob("*.py")):
        parts = path.relative_to(base).parts
        if "tests" in parts or "__pycache__" in parts:
            continue
        yield path


def plan(src: Path, dst: Path) -> tuple[list[Path], list[Path]]:
    """Return ``(to_write, to_delete)`` as ``dst``-relative paths.

    ``to_write`` are source files missing from or differing in ``dst``.
    ``to_delete`` are vendored ``*.py`` files with no source counterpart.
    ``_VENDORED.md`` is never touched.
    """
    src_rels = [p.relative_to(src) for p in _iter_py(src)]

    to_write: list[Path] = []
    for rel in src_rels:
        target = dst / rel
        if not target.exists() or target.read_bytes() != (src / rel).read_bytes():
            to_write.append(rel)

    src_set = set(src_rels)
    to_delete = [
        p.relative_to(dst) for p in _iter_py(dst) if p.relative_to(dst) not in src_set
    ]

    return sorted(to_write), sorted(to_delete)


def apply(src: Path, dst: Path, plan_result: tuple[list[Path], list[Path]]) -> None:
    to_write, to_delete = plan_result
    for rel in to_write:
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes((src / rel).read_bytes())
    for rel in to_delete:
        target = dst / rel
        if target.exists():
            target.unlink()
        parent = target.parent
        while parent != dst and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
            parent = parent.parent


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    root = repo_root()
    src, dst = root / SRC_REL, root / DST_REL
    to_write, to_delete = plan(src, dst)

    if check:
        if to_write or to_delete:
            print("DRIFT:")
            for rel in to_write:
                print(f"  write  {rel}")
            for rel in to_delete:
                print(f"  delete {rel}")
            return 1
        print("vendored core in sync")
        return 0

    apply(src, dst, (to_write, to_delete))
    print(f"synced {len(to_write)} files, removed {len(to_delete)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
