#!/usr/bin/env python3
"""Sync the shared battery card core into the Home Assistant integration.

The Lovelace card ships a *vendored* copy of
``dashboard/internal/webui/static/js/battery-card-core.js``. That copy is a
derived artifact: it is regenerated by this script and never edited by hand.
``--check`` reports drift and is wired into ``git-hooks/pre-commit`` and the
HA test suite (``integrations/homeassistant/tests/test_vendor_card_sync.py``).

Usage (from anywhere inside the repo)::

    .venv/bin/python scripts/vendor_card.py            # sync src -> vendored copy
    .venv/bin/python scripts/vendor_card.py --check    # drift detector (exit 1 on drift)

Stdlib only.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SRC_REL = Path("dashboard/internal/webui/static/js/battery-card-core.js")
DST_REL = Path(
    "integrations/homeassistant/custom_components/battery_soc/www/battery-card-core.js"
)

HEADER = (
    "// AUTOMATISCH ERZEUGT - nicht von Hand aendern.\n"
    "// Quelle: dashboard/internal/webui/static/js/battery-card-core.js\n"
    "// Erneuern mit: .venv/bin/python scripts/vendor_card.py\n"
)


def repo_root() -> Path:
    out = subprocess.check_output(["git", "rev-parse", "--show-toplevel"])
    return Path(out.decode().strip())


def rendered(src: Path) -> str:
    return HEADER + src.read_text(encoding="utf-8")


def plan(src: Path, dst: Path) -> list[str]:
    """Return a one-element list naming the destination when it is stale."""
    if not dst.exists() or dst.read_text(encoding="utf-8") != rendered(src):
        return [str(dst)]
    return []


def main(argv: list[str]) -> int:
    root = repo_root()
    src = root / SRC_REL
    dst = root / DST_REL
    stale = plan(src, dst)
    if "--check" in argv:
        if stale:
            print(f"drift: {stale}", file=sys.stderr)
            return 1
        return 0
    if stale:
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(rendered(src), encoding="utf-8")
        print(f"wrote {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
